### ISSUE TITLE
 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by dayjaby** [ospalh/anki-addons#81]
Right after installing the plugin I clicked on "Type C" in the window where to add new cards. I got the following error: 

    Traceback (most recent call last):
      File "C:\Users\David Jablonski\Documents\Anki\addons\Quick_note_and_deck_buttons.py", line 111, in <lambda>
        l = lambda s=chooser, nn=button_item["name"]: do_function(s, nn)
      File "C:\Users\David Jablonski\Documents\Anki\addons\Quick_note_and_deck_buttons.py", line 130, in change_model_to
        chooser.deck.conf['curModel'] = m['id']
    TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by dayjaby** [comment]
Ah, it seems to be necessary to configure this plugin first. Ignore it!
