### ISSUE TITLE
Download audio: Invalid syntax

### ISSUE THREAD

**Issue by dayjaby** [ospalh/anki-addons#91]
Copy from https://anki.tenderapp.com/discussions/add-ons/8102-syntax-error : 

Traceback (most recent call last): 
  File "aqt\addons.py", line 41, in loadAddons 
  File "E:\Documents\Anki\addons\download_audio.py", line 22, in <module> 
    import downloadaudio.download 
  File "E:\Documents\Anki\addons\downloadaudio\download.py", line 45, in <module> 
    from .downloaders import downloaders 
  File "E:\Documents\Anki\addons\downloadaudio\downloaders\__init__.py", line 20, in <module>
    from .beolingus import BeolingusDownloader 
  File "E:\Documents\Anki\addons\downloadaudio\downloaders\beolingus.py", line 19, in <module> 
    from ..download_entry import Action, DownloadEntry 
  File "E:\Documents\Anki\addons\downloadaudio\download_entry.py", line 118 
    class Action(object):� Add, Keep, Delete, Blacklist = range(0, 4) 
                         ^ 
SyntaxError: invalid syntax

**Comment by ospalh** [comment]
Thanks for mentioning it here. I missed it at tenderapp.

**Comment by ospalh** [comment]
And it’s not a problem in the original code.
